name: Deploy api

on: 
  workflow_dispatch:
    inputs:
      args:
        description: 'Arguments to the remote script'
        required: false
        type: string

jobs:
  build:
    name: Deploy api
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh command in the background using SSH key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_HOST }}
        username: ${{ secrets.DEV_USERNAME }}
        key: ${{ secrets.DEV_DEPLOY_KEY }}
        script: /sw/deploy_api.sh ${{ inputs.args }} &
