name: deploy docs and viewer
on:
    workflow_dispatch:
        # inputs:
        #   args:
        #     description: 'Arguments to the remote script'
        #     required: false
        #     type: string
#   push:
#     branches:
#       - master
#       - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      # - uses: actions/npm-cache
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: git submodule update --init --recursive
      - run: mkdir site
      - run: mkdocs build --config-file docs/mkdocs.yml --site-dir molstar-extension/site/docs
      # - run: mkdocs gh-deploy --config-file docs/mkdocs.yml --force --site-dir molstar-extension/site/docs